/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.abonkentang.view;
import com.mycompany.abonkentang.controller.BahanBakuController;
import com.mycompany.abonkentang.model.BahanBaku;
import javax.swing.JOptionPane;

/**
 *
 * @author Alfikho Azka Dinova - 10125107
 */
public class BahanBakuFrame extends javax.swing.JFrame {
    
    private BahanBakuController controller; 
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BahanBakuFrame.class.getName());
    private boolean isEditMode = false;
    private int selectedIdBahan = -1;
    

    /**
     * Creates new form BahanBakuFrame
     */
    public BahanBakuFrame() {
        initComponents();
        controller = new BahanBakuController();
        controller.tampilData(tblBahanBaku);
        tableWidth();
        getContentPane().setBackground(new java.awt.Color(51,51,51));
        lblBahanBaku.setForeground(java.awt.Color.WHITE);
        btnKembali.setForeground(java.awt.Color.WHITE);
        tblBahanBaku.setRowHeight(25);
        tblBahanBaku.setShowGrid(false);
        tblBahanBaku.setSelectionBackground(new java.awt.Color(47, 128, 237));
        tblBahanBaku.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        clearForm();
    }
    
    private void clearForm() {
        txtNamaBahan.setText("");
        txtStok.setText("");
        txtHarga.setText("");
        cmbSatuan.setSelectedIndex(0);

        tblBahanBaku.clearSelection();

        isEditMode = false;
        selectedIdBahan = -1;

        btnTambah.setText("Tambah");
        btnKosongkan.setText("Kosongkan");
    }
    
    private void tableWidth() {
    tblBahanBaku.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);

    tblBahanBaku.getColumnModel().getColumn(0).setPreferredWidth(40);
    tblBahanBaku.getColumnModel().getColumn(1).setPreferredWidth(180);
    tblBahanBaku.getColumnModel().getColumn(2).setPreferredWidth(80);
    tblBahanBaku.getColumnModel().getColumn(3).setPreferredWidth(60);
    tblBahanBaku.getColumnModel().getColumn(4).setPreferredWidth(120);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new com.mycompany.abonkentang.components.CardPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBahanBaku = new com.mycompany.abonkentang.components.Table();
        jLabel3 = new javax.swing.JLabel();
        panelInput = new com.mycompany.abonkentang.components.CardPanel();
        lblNamaBahan = new javax.swing.JLabel();
        lblStok = new javax.swing.JLabel();
        lblSatuan = new javax.swing.JLabel();
        txtStok = new javax.swing.JTextField();
        cmbSatuan = new javax.swing.JComboBox<>();
        lblHarga = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        txtNamaBahan = new javax.swing.JTextField();
        btnTambah = new com.mycompany.abonkentang.components.Button();
        btnHapus = new com.mycompany.abonkentang.components.Button();
        btnUbah = new com.mycompany.abonkentang.components.Button();
        btnKosongkan = new com.mycompany.abonkentang.components.Button();
        btnKembali = new com.mycompany.abonkentang.components.Button();
        jPanel1 = new com.mycompany.abonkentang.components.CardPanel();
        txtCari = new javax.swing.JTextField();
        btnCari = new com.mycompany.abonkentang.components.Button();
        btnClear = new com.mycompany.abonkentang.components.Button();
        panelTabel = new javax.swing.JPanel();
        lblBahanBaku = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));

        tblBahanBaku.setBackground(new java.awt.Color(70, 71, 174));
        tblBahanBaku.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        tblBahanBaku.setForeground(new java.awt.Color(255, 255, 255));
        tblBahanBaku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Satuan", "Stok", "Harga"
            }
        ));
        tblBahanBaku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBahanBakuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBahanBaku);

        jLabel3.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FORM INPUT");

        panelInput.setBackground(new java.awt.Color(70, 71, 174));

        lblNamaBahan.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        lblNamaBahan.setForeground(new java.awt.Color(255, 255, 255));
        lblNamaBahan.setText("Nama Bahan");

        lblStok.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        lblStok.setForeground(new java.awt.Color(255, 255, 255));
        lblStok.setText("Stok");

        lblSatuan.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        lblSatuan.setForeground(new java.awt.Color(255, 255, 255));
        lblSatuan.setText("Satuan");

        txtStok.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        txtStok.addActionListener(this::txtStokActionPerformed);

        cmbSatuan.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        cmbSatuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kg", "Liter", "Pcs", "Gram" }));
        cmbSatuan.addActionListener(this::cmbSatuanActionPerformed);

        lblHarga.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        lblHarga.setForeground(new java.awt.Color(255, 255, 255));
        lblHarga.setText("Harga");

        txtHarga.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        txtHarga.addActionListener(this::txtHargaActionPerformed);

        txtNamaBahan.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        txtNamaBahan.addActionListener(this::txtNamaBahanActionPerformed);

        javax.swing.GroupLayout panelInputLayout = new javax.swing.GroupLayout(panelInput);
        panelInput.setLayout(panelInputLayout);
        panelInputLayout.setHorizontalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNamaBahan)
                    .addComponent(lblSatuan)
                    .addComponent(lblHarga)
                    .addComponent(lblStok))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtStok, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(txtHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInputLayout.createSequentialGroup()
                        .addComponent(cmbSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addComponent(txtNamaBahan))
                .addGap(31, 31, 31))
        );
        panelInputLayout.setVerticalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaBahan)
                    .addComponent(txtNamaBahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStok)
                    .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSatuan))
                .addGap(16, 16, 16)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHarga)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        btnTambah.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTambah.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTambah.addActionListener(this::btnTambahActionPerformed);

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trash.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHapus.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/shuffle.png"))); // NOI18N
        btnUbah.setText("Edit");
        btnUbah.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUbah.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUbah.addActionListener(this::btnUbahActionPerformed);

        btnKosongkan.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        btnKosongkan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/minus.png"))); // NOI18N
        btnKosongkan.setText("Kosongkan");
        btnKosongkan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKosongkan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKosongkan.addActionListener(this::btnKosongkanActionPerformed);

        btnKembali.setBackground(new java.awt.Color(102, 102, 102));
        btnKembali.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/angle-left.png"))); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);

        jPanel1.setBackground(new java.awt.Color(70, 71, 174));

        txtCari.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        txtCari.setText("Cari");
        txtCari.addActionListener(this::txtCariActionPerformed);

        btnCari.setText("Cari");
        btnCari.setPreferredSize(new java.awt.Dimension(76, 37));
        btnCari.addActionListener(this::btnCariActionPerformed);

        btnClear.setText("Clear");
        btnClear.setPreferredSize(new java.awt.Dimension(76, 37));
        btnClear.addActionListener(this::btnClearActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addGap(150, 150, 150))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnKosongkan, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(panelInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(76, 76, 76)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(panelInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                                    .addComponent(btnKosongkan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))))
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 77, 1146, 470));

        panelTabel.setBackground(new java.awt.Color(17, 46, 129));

        lblBahanBaku.setBackground(new java.awt.Color(255, 255, 255));
        lblBahanBaku.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        lblBahanBaku.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBahanBaku.setText("DATA BAHAN BAKU");

        javax.swing.GroupLayout panelTabelLayout = new javax.swing.GroupLayout(panelTabel);
        panelTabel.setLayout(panelTabelLayout);
        panelTabelLayout.setHorizontalGroup(
            panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBahanBaku, javax.swing.GroupLayout.DEFAULT_SIZE, 1146, Short.MAX_VALUE)
        );
        panelTabelLayout.setVerticalGroup(
            panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabelLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(lblBahanBaku)
                .addGap(27, 27, 27))
        );

        getContentPane().add(panelTabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtCari.setText("");
        controller.tampilData(tblBahanBaku);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        controller.cariByNama(tblBahanBaku, txtCari.getText());
    }//GEN-LAST:event_btnCariActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        new MainFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnKosongkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKosongkanActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btnKosongkanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblBahanBaku.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                "Data harus dipilih sebelum diedit.");
            return;
        }

        // Simpan ID untuk proses update
        selectedIdBahan = Integer.parseInt(
            tblBahanBaku.getValueAt(selectedRow, 0).toString());

        // Isi form dari tabel
        txtNamaBahan.setText(
            tblBahanBaku.getValueAt(selectedRow, 1).toString());

        cmbSatuan.setSelectedItem(
            tblBahanBaku.getValueAt(selectedRow, 2).toString());

        txtStok.setText(
            tblBahanBaku.getValueAt(selectedRow, 3).toString());

        String harga = tblBahanBaku.getValueAt(selectedRow, 4).toString();

        harga = harga.replace("Rp", "")
        .replace(".", "")
        .replace(",", "")
        .trim();

        txtHarga.setText(harga);

        isEditMode = true;

        btnTambah.setText("Simpan Perubahan");
        btnKosongkan.setText("Batal");
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int row = tblBahanBaku.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus terlebih dahulu");
            return;
        }

        int konfirmasi = JOptionPane.showConfirmDialog(
            this,
            "Apakah Anda yakin ingin menghapus data ini?",
            "Konfirmasi Hapus",
            JOptionPane.YES_NO_OPTION
        );

        if (konfirmasi == JOptionPane.YES_OPTION) {
            int id = (int) tblBahanBaku.getValueAt(row, 0);
            controller.hapusData(id);
            controller.tampilData(tblBahanBaku);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        try {

            String nama = txtNamaBahan.getText().trim();
            String satuan = (String) cmbSatuan.getSelectedItem();

            if (nama.isEmpty() || satuan == null) {
                JOptionPane.showMessageDialog(this, "Nama dan satuan wajib diisi");
                return;
            }

            double stok = Double.parseDouble(txtStok.getText());
            double harga = Double.parseDouble(txtHarga.getText());
            if (stok < 0 || harga < 0) {
                JOptionPane.showMessageDialog(this, "Stok dan harga tidak boleh negatif");
                return;
            }

            BahanBaku bb = new BahanBaku();
            bb.setNamaBahan(nama);
            bb.setSatuan(satuan);
            bb.setStokBahan(stok);
            bb.setHargaSatuan(harga);

            if (isEditMode) {

                int selectedRow = tblBahanBaku.getSelectedRow();

                String namaLama = tblBahanBaku.getValueAt(selectedRow, 1).toString();
                String satuanLama = tblBahanBaku.getValueAt(selectedRow, 2).toString();
                double stokLama = Double.parseDouble(tblBahanBaku.getValueAt(selectedRow, 3).toString());

                String hargaText = tblBahanBaku.getValueAt(selectedRow, 4).toString();
                hargaText = hargaText.replace("Rp", "")
                .replace(".", "")
                .replace(",", "")
                .trim();

                double hargaLama = Double.parseDouble(hargaText);

                if (nama.equals(namaLama)
                    && satuan.equals(satuanLama)
                    && Double.compare(stok, stokLama) == 0
                    && Double.compare(harga, hargaLama) == 0) {

                    JOptionPane.showMessageDialog(this,
                        "Anda tidak mengubah apa pun.");
                    return;
                }

                bb.setIdBahan(selectedIdBahan);
                controller.updateData(bb);

            } else {

                controller.simpanData(bb);

            }

            controller.tampilData(tblBahanBaku);
            clearForm();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Stok dan harga harus berupa angka.");

        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void txtNamaBahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaBahanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaBahanActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void cmbSatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSatuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSatuanActionPerformed

    private void txtStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStokActionPerformed

    private void tblBahanBakuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBahanBakuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblBahanBakuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BahanBakuFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnKosongkan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cmbSatuan;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBahanBaku;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblNamaBahan;
    private javax.swing.JLabel lblSatuan;
    private javax.swing.JLabel lblStok;
    private javax.swing.JPanel panelInput;
    private javax.swing.JPanel panelTabel;
    private javax.swing.JTable tblBahanBaku;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtNamaBahan;
    private javax.swing.JTextField txtStok;
    // End of variables declaration//GEN-END:variables
}
