/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.abonkentang.view;
import java.text.SimpleDateFormat;
import com.mycompany.abonkentang.controller.LaporanController;
import com.mycompany.abonkentang.model.LaporanProduksi;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
import java.io.File;
import java.io.FileOutputStream;
import javax.swing.JFileChooser;
import com.lowagie.text.Document;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;

/**
 *
 * @author Alfikho Azka Dinova - 10125107
 */
public class LaporanProduksiFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LaporanProduksiFrame.class.getName());
    private LaporanController controller;
    private final SimpleDateFormat formatTanggal = new SimpleDateFormat("dd-MM-yyyy");

    /**
     * Creates new form LaporanProduksiFrame
     */
    public LaporanProduksiFrame() {
        initComponents();
        controller = new LaporanController();
        getContentPane().setBackground(new java.awt.Color(51,51,51));
        tampilData();
        tableWidth();
        tblLaporan.setRowHeight(25);
        tblLaporan.setShowGrid(false);
        tblLaporan.setSelectionBackground(new java.awt.Color(51,51,51));
        tblLaporan.getTableHeader().setFont(
                new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
    }

    private void tableWidth() {
        tblLaporan.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);

        tblLaporan.getColumnModel().getColumn(0).setPreferredWidth(90);
        tblLaporan.getColumnModel().getColumn(1).setPreferredWidth(200);
        tblLaporan.getColumnModel().getColumn(2).setPreferredWidth(110);
        tblLaporan.getColumnModel().getColumn(3).setPreferredWidth(180);
    }

    private void tampilData() {

        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        model.addColumn("Tanggal Produksi");
        model.addColumn("Nama Produk");
        model.addColumn("Jumlah Produksi");
        model.addColumn("Keterangan");

        List<LaporanProduksi> daftarLaporan = controller.getLaporanProduksi();

        int totalJumlah = 0;

        for (LaporanProduksi lp : daftarLaporan) {

            model.addRow(new Object[]{
                formatTanggal.format(lp.getTanggalProduksi()),
                lp.getNamaProduk(),
                lp.getJumlahProduksi(),
                lp.getKeterangan() == null ? "-" : lp.getKeterangan()
            });

            totalJumlah += lp.getJumlahProduksi();
        }

        tblLaporan.setModel(model);
        lblTotal.setText("Total Jumlah Produksi: " + totalJumlah);
        tableWidth();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblLaporanProduksi = new com.mycompany.abonkentang.components.TitleLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLaporan = new com.mycompany.abonkentang.components.Table();
        lblTotal = new com.mycompany.abonkentang.components.Label();
        btnKembali = new com.mycompany.abonkentang.components.Button();
        btnRefresh = new com.mycompany.abonkentang.components.Button();
        btnExport = new com.mycompany.abonkentang.components.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(17, 46, 129));

        lblLaporanProduksi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLaporanProduksi.setText("Laporan Produksi");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLaporanProduksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblLaporanProduksi)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        tblLaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblLaporan);

        lblTotal.setText("Total Jumlah Produksi:");

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);

        btnExport.setText("Export PDF");
        btnExport.addActionListener(this::btnExportActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotal)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnKembali)
                            .addGap(18, 18, 18)
                            .addComponent(btnRefresh)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExport))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1022, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKembali)
                    .addComponent(btnRefresh)
                    .addComponent(btnExport))
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotal)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        new MainFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        tampilData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setSelectedFile(new File("laporan_produksi.pdf"));
        int pilihan = fileChooser.showSaveDialog(this);
 
        if (pilihan != JFileChooser.APPROVE_OPTION) {
            return;
        }
 
        File file = fileChooser.getSelectedFile();
 
        try {
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream(file));
            document.open();
 
            Font fontJudul = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16);
            Paragraph judul = new Paragraph("Laporan Produksi", fontJudul);
            judul.setAlignment(Paragraph.ALIGN_CENTER);
            document.add(judul);
            document.add(new Paragraph(" "));
 
            PdfPTable tabel = new PdfPTable(4);
            tabel.setWidthPercentage(100);
 
            Font fontHeader = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 11);
            String[] header = {"Tanggal Produksi", "Nama Produk", "Jumlah Produksi", "Keterangan"};
            for (String h : header) {
                tabel.addCell(new PdfPCell(new Phrase(h, fontHeader)));
            }
 
            DefaultTableModel model = (DefaultTableModel) tblLaporan.getModel();
            for (int i = 0; i < model.getRowCount(); i++) {
                for (int j = 0; j < model.getColumnCount(); j++) {
                    Object value = model.getValueAt(i, j);
                    tabel.addCell(String.valueOf(value));
                }
            }
 
            document.add(tabel);
            document.add(new Paragraph(" "));
            document.add(new Paragraph(lblTotal.getText()));
 
            document.close();
 
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Laporan berhasil disimpan ke:\n" + file.getAbsolutePath(),
                    "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);
 
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Gagal membuat PDF: " + e.getMessage(),
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LaporanProduksiFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLaporanProduksi;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblLaporan;
    // End of variables declaration//GEN-END:variables
}
