/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.abonkentang.view;
import com.mycompany.abonkentang.config.Sesi;
import com.mycompany.abonkentang.controller.ProdukController;
import com.mycompany.abonkentang.controller.StokController;
import com.mycompany.abonkentang.controller.TransaksiController;
import java.text.DecimalFormat;
import java.awt.Font;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.BoxLayout;

/**
 *
 * @author Alfikho Azka Dinova - 10125107
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    private final ProdukController produkController = new ProdukController();
    private final StokController stokController = new StokController();
    private final TransaksiController transaksiController = new TransaksiController();
    private final DecimalFormat formatRupiah = new DecimalFormat("#,##0");

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(51,51,51));
        tampilkanStatistik();
        tampilkanNamaUser();
    }
    
    private JLabel buatKartu(javax.swing.JPanel panel, String judul, String nilaiAwal) {
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        panel.setPreferredSize(new java.awt.Dimension(160, 90));

        JLabel lblJudul = new JLabel(judul);
        lblJudul.setForeground(new Color(220, 220, 220));
        lblJudul.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        lblJudul.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);

        JLabel lblNilai = new JLabel(nilaiAwal);
        lblNilai.setForeground(Color.WHITE);
        lblNilai.setFont(new Font("Segoe UI", Font.BOLD, 16));
        lblNilai.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);

        panel.add(javax.swing.Box.createVerticalGlue());
        panel.add(lblJudul);
        panel.add(javax.swing.Box.createVerticalStrut(4));
        panel.add(lblNilai);
        panel.add(javax.swing.Box.createVerticalGlue());

        return lblNilai;
    }

    private void tampilkanStatistik() {
        JLabel lblTotalProduk = buatKartu(jPanel1, "Total Produk", "0");
        JLabel lblStokMenipis = buatKartu(jPanel2, "Stok Menipis", "0");
        JLabel lblPenjualan = buatKartu(jPanel3, "Penjualan Hari Ini", "Rp 0");

        lblTotalProduk.setText(String.valueOf(produkController.hitungTotalProduk()));
        lblStokMenipis.setText(String.valueOf(stokController.hitungStokMenipis()));
        lblPenjualan.setText("Rp " + formatRupiah.format(transaksiController.hitungPenjualanHariIni()));
    }
    
    private void tampilkanNamaUser() {
    if (Sesi.getUser() != null) {
        String nama = Sesi.getUser().getNamaLengkap();
        if (nama == null || nama.trim().isEmpty()) {
            nama = Sesi.getUser().getUsername();
        }
        lblSelamatDatang.setText("Selamat Datang, " + nama);
    } else {
        lblSelamatDatang.setText("Selamat Datang");
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu2 = new javax.swing.JPopupMenu();
        menuLaporanPenjualan = new javax.swing.JMenuItem();
        menuLaporanProduksi = new javax.swing.JMenuItem();
        btnBahanBaku = new com.mycompany.abonkentang.components.Button();
        btnProduk = new com.mycompany.abonkentang.components.Button();
        btnProduksi = new com.mycompany.abonkentang.components.Button();
        btnTransaksi = new com.mycompany.abonkentang.components.Button();
        btnStok = new com.mycompany.abonkentang.components.Button();
        btnLaporan = new com.mycompany.abonkentang.components.Button();
        cardPanel1 = new com.mycompany.abonkentang.components.CardPanel();
        lblTitle = new com.mycompany.abonkentang.components.TitleLabel();
        lblSelamatDatang = new com.mycompany.abonkentang.components.Label();
        jPanel1 = new com.mycompany.abonkentang.components.CardPanel();
        jPanel2 = new com.mycompany.abonkentang.components.CardPanel();
        jPanel3 = new com.mycompany.abonkentang.components.CardPanel();

        menuLaporanPenjualan.setText("Laporan Penjualan");
        menuLaporanPenjualan.addActionListener(this::menuLaporanPenjualanActionPerformed);
        jPopupMenu2.add(menuLaporanPenjualan);

        menuLaporanProduksi.setText("Laporan Produksi");
        menuLaporanProduksi.addActionListener(this::menuLaporanProduksiActionPerformed);
        jPopupMenu2.add(menuLaporanProduksi);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBahanBaku.setText("Bahan Baku");
        btnBahanBaku.addActionListener(this::btnBahanBakuActionPerformed);

        btnProduk.setText("Produk");
        btnProduk.addActionListener(this::btnProdukActionPerformed);

        btnProduksi.setText("Produksi");
        btnProduksi.addActionListener(this::btnProduksiActionPerformed);

        btnTransaksi.setText("Transaksi");
        btnTransaksi.addActionListener(this::btnTransaksiActionPerformed);

        btnStok.setText("Stok");
        btnStok.addActionListener(this::btnStokActionPerformed);

        btnLaporan.setText("Laporan");
        btnLaporan.addActionListener(this::btnLaporanActionPerformed);

        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Sistem Pengelolaan Abon Kentang");

        lblSelamatDatang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSelamatDatang.setText("Selamat Datang");

        javax.swing.GroupLayout cardPanel1Layout = new javax.swing.GroupLayout(cardPanel1);
        cardPanel1.setLayout(cardPanel1Layout);
        cardPanel1Layout.setHorizontalGroup(
            cardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
            .addComponent(lblSelamatDatang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        cardPanel1Layout.setVerticalGroup(
            cardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSelamatDatang)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBahanBaku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnProduk, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(btnStok, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(btnProduksi, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cardPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBahanBaku, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProduksi, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStok, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanActionPerformed
        // TODO add your handling code here:
        jPopupMenu2.show(btnLaporan, 0, btnLaporan.getHeight());
    }//GEN-LAST:event_btnLaporanActionPerformed

    private void menuLaporanPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLaporanPenjualanActionPerformed
        // TODO add your handling code here:
        LaporanPenjualanFrame laporan = new LaporanPenjualanFrame();
        laporan.setLocationRelativeTo(this);
        laporan.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuLaporanPenjualanActionPerformed

    private void menuLaporanProduksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLaporanProduksiActionPerformed
        // TODO add your handling code here:
        LaporanProduksiFrame laporan = new LaporanProduksiFrame();
        laporan.setLocationRelativeTo(this);
        laporan.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuLaporanProduksiActionPerformed

    private void btnBahanBakuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBahanBakuActionPerformed
        // TODO add your handling code here:
        BahanBakuFrame bahan = new BahanBakuFrame();
        bahan.setLocationRelativeTo(this);
        bahan.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBahanBakuActionPerformed

    private void btnProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdukActionPerformed
        // TODO add your handling code here:
        ProdukFrame produk = new ProdukFrame();
        produk.setLocationRelativeTo(this);
        produk.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnProdukActionPerformed

    private void btnProduksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduksiActionPerformed
        // TODO add your handling code here:
        ProduksiFrame produksi = new ProduksiFrame();
        produksi.setLocationRelativeTo(this);
        produksi.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnProduksiActionPerformed

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        // TODO add your handling code here:
        TransaksiFrame transaksi = new TransaksiFrame();
        transaksi.setLocationRelativeTo(this);
        transaksi.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTransaksiActionPerformed

    private void btnStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStokActionPerformed
        // TODO add your handling code here:
        StokFrame stok = new StokFrame();
        stok.setLocationRelativeTo(this);
        stok.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnStokActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBahanBaku;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnProduk;
    private javax.swing.JButton btnProduksi;
    private javax.swing.JButton btnStok;
    private javax.swing.JButton btnTransaksi;
    private com.mycompany.abonkentang.components.CardPanel cardPanel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JLabel lblSelamatDatang;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JMenuItem menuLaporanPenjualan;
    private javax.swing.JMenuItem menuLaporanProduksi;
    // End of variables declaration//GEN-END:variables
}
