/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.abonkentang.view;

import com.mycompany.abonkentang.controller.ProdukController;
import com.mycompany.abonkentang.model.Produk;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rassya Haikal Firdaus - 10125037, Alfikho Azka Dinova - 10125107
 */
public class ProdukFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProdukFrame.class.getName());
    
    private ProdukController controller;
    /**
     * Creates new form ProdukFrame
     */
    private boolean isEditMode = false;
    private String kodeProdukTerpilih;
    public ProdukFrame() {
        initComponents();
        cmbSatuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kg", "Liter", "Pcs", "Pack" }));
        tblProduk.setRowHeight(25);
        tblProduk.setShowGrid(false);
        tblProduk.setSelectionBackground(new java.awt.Color(51, 51, 51));
        tblProduk.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        controller = new ProdukController();
        getContentPane().setBackground(new java.awt.Color(51,51,51));
        tampilData(); 
    }
    
    private void tableWidth() {
    tblProduk.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);

    tblProduk.getColumnModel().getColumn(0).setPreferredWidth(85);
    tblProduk.getColumnModel().getColumn(1).setPreferredWidth(200);
    tblProduk.getColumnModel().getColumn(2).setPreferredWidth(150);
    tblProduk.getColumnModel().getColumn(3).setPreferredWidth(70);
    tblProduk.getColumnModel().getColumn(4).setPreferredWidth(120);
}
    
    private void resetForm() {
        txtKodeProduk.setText("");
        txtNamaProduk.setText("");
        txtKategori.setText("");
        cmbSatuan.setSelectedIndex(0);
        txtHargaJual.setText("");

        isEditMode = false;
        kodeProdukTerpilih = null;
        btnTambah.setText("Tambah");
    }
    
    private void tampilData() {

    DefaultTableModel model = new DefaultTableModel();

    model.addColumn("Kode");
    model.addColumn("Nama Produk");
    model.addColumn("Kategori");
    model.addColumn("Satuan");
    model.addColumn("Harga Jual");

    try {

        List<Produk> daftarProduk = controller.getDataProduk();

        for (Produk p : daftarProduk) {

            model.addRow(new Object[]{
                p.getKodeProduk(),
                p.getNamaProduk(),
                p.getKategori(),
                p.getSatuan(),
                "Rp " + String.format("%,.0f", p.getHargaJual())
            });

        }

        tblProduk.setModel(model);
        tableWidth();

    } catch (Exception e) {
        System.out.println("Gagal tampil data : " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new com.mycompany.abonkentang.components.Label();
        txtKodeProduk = new javax.swing.JTextField();
        jLabel3 = new com.mycompany.abonkentang.components.Label();
        txtNamaProduk = new javax.swing.JTextField();
        jLabel4 = new com.mycompany.abonkentang.components.Label();
        txtKategori = new javax.swing.JTextField();
        jLabel5 = new com.mycompany.abonkentang.components.Label();
        btnTambah = new com.mycompany.abonkentang.components.Button();
        btnEdit = new com.mycompany.abonkentang.components.Button();
        btnHapus = new com.mycompany.abonkentang.components.Button();
        btnBersih = new com.mycompany.abonkentang.components.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduk = new com.mycompany.abonkentang.components.Table();
        txtHargaJual = new javax.swing.JTextField();
        jLabel6 = new com.mycompany.abonkentang.components.Label();
        cmbSatuan = new com.mycompany.abonkentang.components.ComboBox<>();
        jPanel1 = new com.mycompany.abonkentang.components.CardPanel();
        lblDataProduk = new com.mycompany.abonkentang.components.TitleLabel();
        btnKembali = new com.mycompany.abonkentang.components.Button();
        cmbKolomCari = new com.mycompany.abonkentang.components.ComboBox<>();
        txtCariProduk = new javax.swing.JTextField();
        btnCariProduk = new com.mycompany.abonkentang.components.Button();
        btnRefresh = new com.mycompany.abonkentang.components.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Kode Produk");

        txtKodeProduk.addActionListener(this::txtKodeProdukActionPerformed);

        jLabel3.setText("Nama Produk");

        txtNamaProduk.addActionListener(this::txtNamaProdukActionPerformed);

        jLabel4.setText("Kategori  ");

        jLabel5.setText("Satuan");

        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(this::btnTambahActionPerformed);

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/shuffle.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trash.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        btnBersih.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/minus.png"))); // NOI18N
        btnBersih.setText("Kosongkan");
        btnBersih.addActionListener(this::btnBersihActionPerformed);

        jScrollPane1.setBackground(new java.awt.Color(70, 71, 174));

        tblProduk.setBackground(new java.awt.Color(70, 71, 174));
        tblProduk.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        tblProduk.setForeground(new java.awt.Color(255, 255, 255));
        tblProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProduk);

        jLabel6.setText("Harga Jual ");

        cmbSatuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kg", "Liter", "Pcs" }));

        jPanel1.setBackground(new java.awt.Color(17, 46, 129));

        lblDataProduk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDataProduk.setText("DATA PRODUK");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDataProduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblDataProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/angle-left.png"))); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);

        cmbKolomCari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kode Produk", "Nama Produk", "Kategori" }));

        txtCariProduk.setText("Cari Produk");

        btnCariProduk.setText("Cari");
        btnCariProduk.addActionListener(this::btnCariProdukActionPerformed);

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refresh.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jLabel6))
                                        .addGap(114, 114, 114))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(87, 87, 87)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNamaProduk)
                                    .addComponent(txtKategori)
                                    .addComponent(txtKodeProduk)
                                    .addComponent(txtHargaJual)
                                    .addComponent(cmbSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBersih, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCariProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbKolomCari, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCariProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)))
                        .addGap(40, 40, 40))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnKembali, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(txtCariProduk)
                    .addComponent(cmbKolomCari)
                    .addComponent(btnCariProduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtKodeProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNamaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmbSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBersih, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaProdukActionPerformed
        System.out.println("Tombol Simpan itekan");
    }//GEN-LAST:event_txtNamaProdukActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
            int row = tblProduk.getSelectedRow();
            if (row == -1) {
                javax.swing.JOptionPane.showMessageDialog(this, "Pilih data yang ingin diedit terlebih dahulu");
                return;
            }

            kodeProdukTerpilih = tblProduk.getValueAt(row, 0).toString();

            txtKodeProduk.setText(kodeProdukTerpilih);
            txtNamaProduk.setText(tblProduk.getValueAt(row, 1).toString());
            txtKategori.setText(tblProduk.getValueAt(row, 2).toString());
            cmbSatuan.setSelectedItem(tblProduk.getValueAt(row, 3).toString());
            String hargaTampil = tblProduk.getValueAt(row, 4).toString();
            hargaTampil = hargaTampil.replace("Rp", "")
                    .replace(".", "")
                    .replace(",", "")
                    .trim();
            txtHargaJual.setText(hargaTampil);

            isEditMode = true;
            btnTambah.setText("Simpan");
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBersihActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_btnBersihActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
            int row = tblProduk.getSelectedRow();
            if (row == -1) {
                javax.swing.JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus terlebih dahulu");
                return;
            }

            int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(
                    this, "Apakah Anda yakin ingin menghapus data ini?",
                    "Konfirmasi Hapus", javax.swing.JOptionPane.YES_NO_OPTION);

            if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
                String kode = tblProduk.getValueAt(row, 0).toString();

                if (controller.hapusProduk(kode)) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Gagal menghapus data");
                }

                tampilData();
                resetForm();
            }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtKodeProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodeProdukActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        String kode = txtKodeProduk.getText().trim();
        String nama = txtNamaProduk.getText().trim();
        String kategori = txtKategori.getText().trim();
        String satuan = (String) cmbSatuan.getSelectedItem();

        if (kode.isEmpty() || nama.isEmpty() || kategori.isEmpty() || satuan == null
                || txtHargaJual.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Semua kolom wajib diisi!");
            return;
        }

        double harga;
        try {
            harga = Double.parseDouble(txtHargaJual.getText().trim());
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Harga Jual harus berupa angka!");
            return;
        }
        
        if (harga <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Harga Jual harus lebih besar dari 0!");
            return;
        }

        Produk produk = new Produk();
        produk.setKodeProduk(kode);
        produk.setNamaProduk(nama);
        produk.setKategori(kategori);
        produk.setSatuan(satuan);
        produk.setHargaJual(harga);

        if (isEditMode) {
            if (controller.updateProduk(kodeProdukTerpilih, produk)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil diubah");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal mengubah data");
            }
        } else {
            if (controller.simpanProduk(produk)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal menyimpan data");
            }
        }

        tampilData();
        resetForm();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        new MainFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnCariProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariProdukActionPerformed
        // TODO add your handling code here:
        String keyword = txtCariProduk.getText().trim();
        String pilihan = (String) cmbKolomCari.getSelectedItem();

        if (keyword.isEmpty()) {
            tampilData();
            return;
        }

        String kolom;
        switch (pilihan) {
            case "Kode Produk": kolom = "kode_produk"; break;
            case "Kategori": kolom = "kategori"; break;
            default: kolom = "nama_produk"; break;
        }

        try {
            List<Produk> hasil = controller.cariProduk(keyword, kolom);
            DefaultTableModel model = (DefaultTableModel) tblProduk.getModel();
            model.setRowCount(0);
            for (Produk p : hasil) {
                model.addRow(new Object[]{
                    p.getKodeProduk(), p.getNamaProduk(), p.getKategori(),
                    p.getSatuan(), p.getHargaJual()
                });
            }
        } catch (RuntimeException e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnCariProdukActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        tampilData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ProdukFrame().setVisible(true));
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBersih;
    private javax.swing.JButton btnCariProduk;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cmbKolomCari;
    private javax.swing.JComboBox<String> cmbSatuan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDataProduk;
    private javax.swing.JTable tblProduk;
    private javax.swing.JTextField txtCariProduk;
    private javax.swing.JTextField txtHargaJual;
    private javax.swing.JTextField txtKategori;
    private javax.swing.JTextField txtKodeProduk;
    private javax.swing.JTextField txtNamaProduk;
    // End of variables declaration//GEN-END:variables
}
